name: CI for Django Project

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Set working directory
      run: |
        cd ./myapp
    - name: List files in the Docker build context
      run: |
        ls -l ./myapp
    - name: Build Docker image
      run: |
        docker build -f ./myapp/Dockerfile -t my-django-app ./myapp
        docker run -d -p 8000:8000 my-django-app

    - name: Install dependencies
      run: |
        pip install -r ./myapp/requirements.txt

    - name: Run migrations
      run: |
        python ./myapp/manage.py migrate


    - name: Clean up Docker containers
      run: |
        docker stop $(docker ps -aq)
        docker rm $(docker ps -aq)
